INSERT INTO achievements (achievement_id, file_name, achievement_name, achievement_description)
VALUES
    (1, 'osu-skill-pass-1', 'Rising Star', 'Can''t go forward without the first steps.'),
    (2, 'osu-skill-pass-2', 'Constellation Prize', 'Definitely not a consolation prize. Now things start getting hard!'),
    (3, 'osu-skill-pass-3', 'Building Confidence', 'Oh, you''ve SO got this.'),
    (4, 'osu-skill-pass-4', 'Insanity Approaches', 'You''re not twitching, you''re just ready.'),
    (5, 'osu-skill-pass-5', 'These Clarion Skies', 'Everything seems so clear now.'),
    (6, 'osu-skill-pass-6', 'Above and Beyond', 'A cut above the rest.'),
    (7, 'osu-skill-pass-7', 'Supremacy', 'All marvel before your prowess.'),
    (8, 'osu-skill-pass-8', 'Absolution', 'My god, you''re full of stars!'),
    (9, 'osu-skill-pass-9', 'Event Horizon', 'No force dares to pull you under.'),
    (10, 'osu-skill-pass-10', 'Phantasm', 'Fevered is your passion, extraordinary is your skill.'),
    (11, 'osu-skill-fc-1', 'Totality', 'All the notes. Every single one.'),
    (12, 'osu-skill-fc-2', 'Business As Usual', 'Two to go, please.'),
    (13, 'osu-skill-fc-3', 'Building Steam', 'Hey, this isn''t so bad.'),
    (14, 'osu-skill-fc-4', 'Moving Forward', 'Bet you feel good about that.'),
    (15, 'osu-skill-fc-5', 'Paradigm Shift', 'Surprisingly difficult.'),
    (16, 'osu-skill-fc-6', 'Anguish Quelled', 'Don''t choke.'),
    (17, 'osu-skill-fc-7', 'Never Give Up', 'Excellence is its own reward.'),
    (18, 'osu-skill-fc-8', 'Aberration', 'They said it couldn''t be done. They were wrong.'),
    (19, 'osu-skill-fc-9', 'Chosen', 'Reign among the Prometheans, where you belong.'),
    (20, 'osu-skill-fc-10', 'Unfathomable', 'You have no equal.'),
    (21, 'osu-combo-500', '500 Combo', '500 big ones! You''re moving up in the world!'),
    (22, 'osu-combo-750', '750 Combo', '750 notes back to back? Woah.'),
    (23, 'osu-combo-1000', '1000 Combo', 'A thousand reasons why you rock at this game.'),
    (24, 'osu-combo-2000', '2000 Combo', 'Nothing can stop you now.'),
    (25, 'taiko-skill-pass-1', 'My First Don', 'Marching to the beat of your own drum. Literally.'),
    (26, 'taiko-skill-pass-2', 'Katsu Katsu Katsu', 'Hora! Izuko!'),
    (27, 'taiko-skill-pass-3', 'Not Even Trying', 'Muzukashii? Not even.'),
    (28, 'taiko-skill-pass-4', 'Face Your Demons', 'The first trials are now behind you, but are you a match for the Oni?'),
    (29, 'taiko-skill-pass-5', 'The Demon Within', 'No rest for the wicked.'),
    (30, 'taiko-skill-pass-6', 'Drumbreaker', 'Too strong.'),
    (31, 'taiko-skill-pass-7', 'The Godfather', 'You are the Don of Dons.'),
    (32, 'taiko-skill-pass-8', 'Rhythm Incarnate', 'Feel the beat. Become the beat.'),
    (33, 'taiko-skill-fc-1', 'Keeping Time', 'Don, then katsu. Don, then katsu..'),
    (34, 'taiko-skill-fc-2', 'To Your Own Beat', 'Straight and steady.'),
    (35, 'taiko-skill-fc-3', 'Big Drums', 'Bigger scores to match.'),
    (36, 'taiko-skill-fc-4', 'Adversity Overcome', 'Difficult? Not for you.'),
    (37, 'taiko-skill-fc-5', 'Demonslayer', 'An Oni felled forevermore.'),
    (38, 'taiko-skill-fc-6', 'Rhythm''s Call', 'Heralding true skill.'),
    (39, 'taiko-skill-fc-7', 'Time Everlasting', 'Not a single beat escapes you.'),
    (40, 'taiko-skill-fc-8', 'The Drummer''s Throne', 'Percussive brilliance befitting royalty alone.'),
    (41, 'fruits-skill-pass-1', 'A Slice Of Life', 'Hey, this fruit catching business isn''t bad.'),
    (42, 'fruits-skill-pass-2', 'Dashing Ever Forward', 'Fast is how you do it.'),
    (43, 'fruits-skill-pass-3', 'Zesty Disposition', 'No scurvy for you, not with that much fruit.'),
    (44, 'fruits-skill-pass-4', 'Hyperdash ON!', 'Time and distance is no obstacle to you.'),
    (45, 'fruits-skill-pass-5', 'It''s Raining Fruit', 'And you can catch them all.'),
    (46, 'fruits-skill-pass-6', 'Fruit Ninja', 'Legendary techniques.'),
    (47, 'fruits-skill-pass-7', 'Dreamcatcher', 'No fruit, only dreams now.'),
    (48, 'fruits-skill-pass-8', 'Lord of the Catch', 'Your kingdom kneels before you.'),
    (49, 'fruits-skill-fc-1', 'Sweet And Sour', 'Apples and oranges, literally.'),
    (50, 'fruits-skill-fc-2', 'Reaching The Core', 'The seeds of future success.'),
    (51, 'fruits-skill-fc-3', 'Clean Platter', 'Clean only of failure. It is completely full, otherwise.'),
    (52, 'fruits-skill-fc-4', 'Between The Rain', 'No umbrella needed.'),
    (53, 'fruits-skill-fc-5', 'Addicted', 'That was an overdose?'),
    (54, 'fruits-skill-fc-6', 'Quickening', 'A dash above normal limits.'),
    (55, 'fruits-skill-fc-7', 'Supersonic', 'Faster than is reasonably necessary.'),
    (56, 'fruits-skill-fc-8', 'Dashing Scarlet', 'Speed beyond mortal reckoning.'),
    (57, 'mania-skill-pass-1', 'First Steps', 'It isn''t 9-to-5, but 1-to-9. Keys, that is.'),
    (58, 'mania-skill-pass-2', 'No Normal Player', 'Not anymore, at least.'),
    (59, 'mania-skill-pass-3', 'Impulse Drive', 'Not quite hyperspeed, but getting close.'),
    (60, 'mania-skill-pass-4', 'Hyperspeed', 'Woah.'),
    (61, 'mania-skill-pass-5', 'Ever Onwards', 'Another challenge is just around the corner.'),
    (62, 'mania-skill-pass-6', 'Another Surpassed', 'Is there no limit to your skills?'),
    (63, 'mania-skill-pass-7', 'Extra Credit', 'See me after class.'),
    (64, 'mania-skill-pass-8', 'Maniac', 'There''s just no stopping you.'),
    (65, 'mania-skill-fc-1', 'Keystruck', 'The beginning of a new story'),
    (66, 'mania-skill-fc-2', 'Keying In', 'Finding your groove.'),
    (67, 'mania-skill-fc-3', 'Hyperflow', 'You can *feel* the rhythm.'),
    (68, 'mania-skill-fc-4', 'Breakthrough', 'Many skills mastered, rolled into one.'),
    (69, 'mania-skill-fc-5', 'Everything Extra', 'Giving your all is giving everything you have.'),
    (70, 'mania-skill-fc-6', 'Level Breaker', 'Finesse beyond reason'),
    (71, 'mania-skill-fc-7', 'Step Up', 'A precipice rarely seen.'),
    (72, 'mania-skill-fc-8', 'Behind The Veil', 'Supernatural!'),
    (73, 'all-intro-suddendeath', 'Finality', 'High stakes, no regrets.'),
    (74, 'all-intro-hidden', 'Blindsight', 'I can see just perfectly'),
    (75, 'all-intro-perfect', 'Perfectionist', 'Accept nothing but the best.'),
    (76, 'all-intro-hardrock', 'Rock Around The Clock', 'You can''t stop the rock.'),
    (77, 'all-intro-doubletime', 'Time And A Half', 'Having a right ol'' time. One and a half of them, almost.'),
    (78, 'all-intro-flashlight', 'Are You Afraid Of The Dark?', 'Harder than it looks, probably because it''s hard to look.'),
    (79, 'all-intro-easy', 'Dial It Right Back', 'Sometimes you just want to take it easy.'),
    (80, 'all-intro-nofail', 'Risk Averse', 'Safety nets are fun!'),
    (81, 'all-intro-nightcore', 'Sweet Rave Party', 'Founded in the fine tradition of changing things that were just fine as they were.'),
    (82, 'all-intro-halftime', 'Slowboat', 'You got there. Eventually.'),
    (83, 'all-intro-spunout', 'Burned Out', 'One cannot always spin to win.');
